mosquitto_pub -h localhost -t TO_FLASK -m "P3,0,2"
mosquitto_pub -h localhost -t TO_FLASK -m "P3,1,2"
mosquitto_pub -h localhost -t TO_FLASK -m "P3,2,2"
mosquitto_pub -h localhost -t TO_FLASK -m "P3,3,2"
mosquitto_pub -h localhost -t TO_FLASK -m "P3,4,2"
mosquitto_pub -h localhost -t TO_FLASK -m "P3,5,2"
mosquitto_pub -h localhost -t TO_FLASK -m "P3,6,2"
mosquitto_pub -h localhost -t TO_FLASK -m "P3,7,2"
mosquitto_pub -h localhost -t TO_FLASK -m "P3,8,2"
mosquitto_pub -h localhost -t TO_FLASK -m "P3,9,2"

